
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Booking extends javax.swing.JFrame {
    private String pricestd_total;
    private String pricepro_total;
    private String curr_username;
    
    public Booking() {
        initComponents();
        setBounds(100,200,1100,665);
        setLocation(0,0);
        billheader();
    }

    protected void setLoggedInUser(String input){
        curr_username=input;
        name.setText(curr_username);
    }
    protected void setPriceStd(String input){
        pricestd_total=input;
        pricingsstd.setText(pricestd_total);
    }
    protected void setPricePro(String input){
        pricepro_total=input;
        pricingspro.setText(pricepro_total);
    }

    private void billheader(){
        bill.setText("===================="+"\n"
        +"      Wedding Planner"+"\n"
        +"===================="+"\n\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jname = new javax.swing.JLabel();
        jPricingstd = new javax.swing.JLabel();
        jPricingpro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pricingsstd = new javax.swing.JLabel();
        pricingspro = new javax.swing.JLabel();
        jback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        std = new javax.swing.JRadioButton();
        pro = new javax.swing.JRadioButton();
        jcalculate = new javax.swing.JButton();
        totalamount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        generatebill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jname.setText("Name");
        jPanel1.add(jname);
        jname.setBounds(60, 100, 80, 30);

        jPricingstd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingstd.setText("Pricings (Standard)");
        jPanel1.add(jPricingstd);
        jPricingstd.setBounds(60, 170, 160, 30);

        jPricingpro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingpro.setText("Pricings (Professional)");
        jPanel1.add(jPricingpro);
        jPricingpro.setBounds(60, 240, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Hours Needed");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 320, 130, 30);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(name);
        name.setBounds(260, 100, 190, 30);

        pricingsstd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pricingsstd);
        pricingsstd.setBounds(260, 160, 190, 40);

        pricingspro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pricingspro);
        pricingspro.setBounds(260, 240, 190, 30);

        jback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jback.setText("GO BACK");
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });
        jPanel1.add(jback);
        jback.setBounds(580, 540, 150, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Service Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 400, 120, 30);

        hours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursActionPerformed(evt);
            }
        });
        jPanel1.add(hours);
        hours.setBounds(260, 310, 190, 40);

        buttonGroup1.add(std);
        std.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std.setText("Standard");
        jPanel1.add(std);
        std.setBounds(260, 390, 130, 40);

        buttonGroup1.add(pro);
        pro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pro.setText("Professional");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jPanel1.add(pro);
        pro.setBounds(390, 390, 150, 40);

        jcalculate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcalculate.setText("CALCULATE");
        jcalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalculateActionPerformed(evt);
            }
        });
        jPanel1.add(jcalculate);
        jcalculate.setBounds(60, 490, 170, 50);

        totalamount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totalamount);
        totalamount.setBounds(270, 490, 160, 50);

        bill.setEditable(false);
        bill.setColumns(20);
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(580, 60, 441, 368);

        generatebill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generatebill.setText("GENERATE BILL");
        generatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillActionPerformed(evt);
            }
        });
        jPanel1.add(generatebill);
        generatebill.setBounds(580, 450, 440, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
        Details menu = new Details();
        menu.setLoggedInUser(curr_username);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jbackActionPerformed

    private void hoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void jcalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalculateActionPerformed
        // TODO add your handling code here:
        double value4 = Double.parseDouble(hours.getText());
        String vendor="Vendor";
        if(std.isSelected()){
            double valuex = Double.parseDouble(pricestd_total)*value4;
            String result = String.format("%.0f", valuex);
            totalamount.setText(result);
            bill.setText(
                    bill.getText()+"Vendor         --        Pricing   --   Hours   --   Total\n"+
                                    vendor+"   --   "+pricestd_total+"   --   "+value4+"   --   "+result
            );
        }
        if(pro.isSelected()){
            double valuex = Double.parseDouble(pricepro_total)*value4;
            String result = String.format("%.0f", valuex);
            totalamount.setText(result);
            bill.setText(
                    bill.getText()+"Vendor         --        Pricing   --   Hours   --   Total\n"+
                                    vendor+"   --   "+pricepro_total+"   --   "+value4+"   --   "+result
            );
        }
    }//GEN-LAST:event_jcalculateActionPerformed

    private void generatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillActionPerformed
        try {
            bill.print();
        } catch (PrinterException ex) {
            
        }
    }//GEN-LAST:event_generatebillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton generatebill;
    private javax.swing.JTextField hours;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPricingpro;
    private javax.swing.JLabel jPricingstd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jback;
    private javax.swing.JButton jcalculate;
    private javax.swing.JLabel jname;
    public static javax.swing.JLabel name;
    public static javax.swing.JLabel pricingspro;
    public static javax.swing.JLabel pricingsstd;
    private javax.swing.JRadioButton pro;
    private javax.swing.JRadioButton std;
    private javax.swing.JLabel totalamount;
    // End of variables declaration//GEN-END:variables
}
