
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PraveenAnandhanathan
 */
public class Details extends javax.swing.JFrame {
    private String pricestd_final;
    private String pricepro_final;
    private String curr_username;
    private int entries_no;
    private String name_selected;
    private String area_selected;
    private String service_selected;
//    private String pricestd_selected;
//    private String pricepro_selected;
//    private String contact_selected;
//    private String email_selected;
    
    public Details() {
        initComponents();
        setBounds(100,200,1100,665);
        setLocation(0,0);
        entries_no=0;
        pricestd_final="0";
        pricepro_final="0";
    }
    
    protected void setLoggedInUser(String input){
        curr_username=input;
        displayUsr.setText(curr_username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDisplayTable = new javax.swing.JTable();
        book = new javax.swing.JButton();
        jNameTag = new javax.swing.JLabel();
        jServicesTag = new javax.swing.JLabel();
        jPhonenumTag = new javax.swing.JLabel();
        jAddressTag = new javax.swing.JLabel();
        jEmailTag = new javax.swing.JLabel();
        jPricingStdTag = new javax.swing.JLabel();
        jPricingProTag = new javax.swing.JLabel();
        displayUsr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addvalue = new javax.swing.JButton();
        jName = new javax.swing.JComboBox<>();
        jPricepro = new javax.swing.JLabel();
        jContact = new javax.swing.JLabel();
        jMail = new javax.swing.JLabel();
        jPricestd = new javax.swing.JLabel();
        jArea = new javax.swing.JComboBox<>();
        jServicesList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPanel1.setLayout(null);

        jDisplayTable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Name", "Services", "Contact", "Area", "Email", "Pricings (Standard)", "Pricings (Professional)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDisplayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDisplayTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(507, 110, 520, 380);

        book.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book);
        book.setBounds(510, 530, 100, 50);

        jNameTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNameTag.setText("Name");
        jPanel1.add(jNameTag);
        jNameTag.setBounds(60, 240, 90, 22);

        jServicesTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jServicesTag.setText("Serivces");
        jPanel1.add(jServicesTag);
        jServicesTag.setBounds(60, 140, 100, 22);

        jPhonenumTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPhonenumTag.setText("Phone Number");
        jPanel1.add(jPhonenumTag);
        jPhonenumTag.setBounds(60, 300, 140, 22);

        jAddressTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddressTag.setText("Area");
        jPanel1.add(jAddressTag);
        jAddressTag.setBounds(60, 190, 100, 22);

        jEmailTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jEmailTag.setText("Email");
        jPanel1.add(jEmailTag);
        jEmailTag.setBounds(60, 340, 80, 40);

        jPricingStdTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingStdTag.setText("Pricings (Standard)");
        jPanel1.add(jPricingStdTag);
        jPricingStdTag.setBounds(60, 400, 160, 22);

        jPricingProTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingProTag.setText("Pricings (Professional)");
        jPanel1.add(jPricingProTag);
        jPricingProTag.setBounds(60, 460, 180, 22);

        displayUsr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(displayUsr);
        displayUsr.setBounds(841, 30, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.setPreferredSize(new java.awt.Dimension(289, 265));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(940, 30, 110, 30);

        addvalue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addvalue.setText("Add");
        addvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvalueActionPerformed(evt);
            }
        });
        jPanel1.add(addvalue);
        addvalue.setBounds(350, 530, 100, 50);

        jName.setEditable(true);
        jName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ram", "Jony", "Rahim", "Ross" }));
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        jPanel1.add(jName);
        jName.setBounds(260, 230, 190, 40);

        jPricepro.setBackground(new java.awt.Color(204, 204, 255));
        jPricepro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPricepro);
        jPricepro.setBounds(260, 450, 190, 40);

        jContact.setBackground(new java.awt.Color(204, 204, 255));
        jContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jContact);
        jContact.setBounds(260, 290, 190, 40);

        jMail.setBackground(new java.awt.Color(204, 204, 255));
        jMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jMail);
        jMail.setBounds(260, 340, 190, 40);

        jPricestd.setBackground(new java.awt.Color(204, 204, 255));
        jPricestd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPricestd);
        jPricestd.setBounds(260, 390, 190, 40);

        jArea.setEditable(true);
        jArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Haldiram", "Sealdha", "America" }));
        jArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaActionPerformed(evt);
            }
        });
        jPanel1.add(jArea);
        jArea.setBounds(260, 180, 190, 40);

        jServicesList.setEditable(true);
        jServicesList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cooking", "Lighting", "Photography", "Flower Decor" }));
        jServicesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jServicesListActionPerformed(evt);
            }
        });
        jPanel1.add(jServicesList);
        jServicesList.setBounds(260, 130, 190, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed

    
        try{
                JOptionPane.showMessageDialog(null, "Booking");
                Booking menu = new Booking();
                menu.setLoggedInUser(curr_username);
                menu.setPriceStd(pricestd_final);
                menu.setPricePro(pricepro_final);
                menu.setVisible(true);
                setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                Login menu = new Login();
                menu.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisplayTableMouseClicked

    }//GEN-LAST:event_jDisplayTableMouseClicked

    private void addvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvalueActionPerformed
                try{
                    DefaultTableModel model = (DefaultTableModel)jDisplayTable.getModel();
                    Object[] row = new Object[8];
                    row[0]=entries_no++;
                    row[1]=name_selected;
                    row[2]=service_selected;
                    row[3]=jContact.getText();
                    row[4]=area_selected;
                    row[5]=jMail.getText();
                    row[6]=jPricestd.getText();
                    row[7]=jPricepro.getText();
                    pricestd_final=String.valueOf(Integer.parseInt(pricestd_final)+Integer.parseInt(jPricestd.getText()));
                    pricepro_final=String.valueOf(Integer.parseInt(pricepro_final)+Integer.parseInt(jPricepro.getText()));
                    model.addRow(row);
                    JOptionPane.showMessageDialog(null, "Added");
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_addvalueActionPerformed

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // Third List
        name_selected=jName.getSelectedItem().toString();
        if(name_selected == "Ram"){
            jContact.setText("1234");
            jMail.setText(name_selected+"@example.co");
            jPricestd.setText("100");
            jPricepro.setText("200");
        }
        else if(name_selected=="Jony"){
            jContact.setText("1234");
            jMail.setText(name_selected+"@example.co");
            jPricestd.setText("1000");
            jPricepro.setText("2000");
        }
        else if(name_selected=="Rahim"){
            jContact.setText("1234");
            jMail.setText(name_selected+"@example.co");
            jPricestd.setText("100");
            jPricepro.setText("200");
        }
        else if(name_selected=="Ross"){
            jContact.setText("123456");
            jMail.setText(name_selected+"@example.co");
            jPricestd.setText("200");
            jPricepro.setText("300");
        }
        else{
            name_selected="NA";
            jContact.setText("NA");
            jMail.setText(name_selected+"@example.co");
            jPricestd.setText("NA");
            jPricepro.setText("NA");
        }
    }//GEN-LAST:event_jNameActionPerformed

    private void jAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaActionPerformed
        // Second List
        area_selected=jArea.getSelectedItem().toString();
    }//GEN-LAST:event_jAreaActionPerformed

    private void jServicesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jServicesListActionPerformed
        // First List
        service_selected=jServicesList.getSelectedItem().toString();
    }//GEN-LAST:event_jServicesListActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvalue;
    private javax.swing.JButton book;
    public static javax.swing.JLabel displayUsr;
    private javax.swing.JLabel jAddressTag;
    private javax.swing.JComboBox<String> jArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jContact;
    private javax.swing.JTable jDisplayTable;
    private javax.swing.JLabel jEmailTag;
    private javax.swing.JLabel jMail;
    private javax.swing.JComboBox<String> jName;
    private javax.swing.JLabel jNameTag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPhonenumTag;
    private javax.swing.JLabel jPricepro;
    private javax.swing.JLabel jPricestd;
    private javax.swing.JLabel jPricingProTag;
    private javax.swing.JLabel jPricingStdTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jServicesList;
    private javax.swing.JLabel jServicesTag;
    // End of variables declaration//GEN-END:variables
}
