
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PraveenAnandhanathan
 */
public class Details extends javax.swing.JFrame {
    private String name_final;
    private String pricestd_final;
    private String pricepro_final;
    private String curr_username;
    private int entries_no;
    
    public Details() {
        initComponents();
        setBounds(100,200,1100,665);
        setLocation(0,0);
        entries_no=0;
        pricestd_final="0";
        pricepro_final="0";
    }
    
    protected void setLoggedInUser(String input){
        curr_username=input;
        displayUsr.setText(curr_username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDisplayTable = new javax.swing.JTable();
        book = new javax.swing.JButton();
        jNameTag = new javax.swing.JLabel();
        jServicesTag = new javax.swing.JLabel();
        jPhonenumTag = new javax.swing.JLabel();
        jAddressTag = new javax.swing.JLabel();
        jEmailTag = new javax.swing.JLabel();
        jPricingStdTag = new javax.swing.JLabel();
        jPricingProTag = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        services = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pricingstd = new javax.swing.JTextField();
        pricingpro = new javax.swing.JTextField();
        displayUsr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addvalue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPanel1.setLayout(null);

        jDisplayTable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Name", "Services", "Contact", "Address", "Email", "Pricings (Standard)", "Pricings (Professional)"
            }
        ));
        jDisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDisplayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDisplayTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(507, 110, 520, 380);

        book.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book);
        book.setBounds(510, 530, 100, 50);

        jNameTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNameTag.setText("Name");
        jPanel1.add(jNameTag);
        jNameTag.setBounds(60, 110, 90, 22);

        jServicesTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jServicesTag.setText("Serivces");
        jPanel1.add(jServicesTag);
        jServicesTag.setBounds(60, 170, 100, 22);

        jPhonenumTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPhonenumTag.setText("Phone Number");
        jPanel1.add(jPhonenumTag);
        jPhonenumTag.setBounds(60, 230, 140, 22);

        jAddressTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddressTag.setText("Address");
        jPanel1.add(jAddressTag);
        jAddressTag.setBounds(60, 290, 100, 22);

        jEmailTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jEmailTag.setText("Email");
        jPanel1.add(jEmailTag);
        jEmailTag.setBounds(60, 340, 80, 40);

        jPricingStdTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingStdTag.setText("Pricings (Standard)");
        jPanel1.add(jPricingStdTag);
        jPricingStdTag.setBounds(60, 400, 160, 22);

        jPricingProTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPricingProTag.setText("Pricings (Professional)");
        jPanel1.add(jPricingProTag);
        jPricingProTag.setBounds(60, 460, 180, 22);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(260, 110, 190, 40);

        services.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesActionPerformed(evt);
            }
        });
        jPanel1.add(services);
        services.setBounds(260, 160, 190, 40);

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(260, 220, 190, 40);

        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(260, 280, 190, 40);

        email.setEditable(false);
        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(email);
        email.setBounds(260, 340, 190, 40);

        pricingstd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pricingstd);
        pricingstd.setBounds(260, 400, 190, 40);

        pricingpro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pricingpro);
        pricingpro.setBounds(260, 450, 190, 40);

        displayUsr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(displayUsr);
        displayUsr.setBounds(841, 30, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.setPreferredSize(new java.awt.Dimension(289, 265));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(940, 30, 110, 30);

        addvalue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addvalue.setText("Add");
        addvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvalueActionPerformed(evt);
            }
        });
        jPanel1.add(addvalue);
        addvalue.setBounds(350, 530, 100, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed

    
        try{
                JOptionPane.showMessageDialog(null, "Booking");
                Booking menu = new Booking();
                menu.setLoggedInUser(curr_username);
                menu.setPriceStd(pricestd_final);
                menu.setPricePro(pricepro_final);
                menu.setVisible(true);
                setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bookActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
    }//GEN-LAST:event_addressActionPerformed

    private void servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesActionPerformed
    }//GEN-LAST:event_servicesActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
    }//GEN-LAST:event_phoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                Login menu = new Login();
                menu.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisplayTableMouseClicked
        int i = jDisplayTable.getSelectedRow();
        TableModel model =jDisplayTable.getModel();
        name.setText(model.getValueAt(i,1).toString());
        services.setText(model.getValueAt(i,2).toString());
        phone.setText(model.getValueAt(i,3).toString());
        address.setText(model.getValueAt(i,4).toString());
        email.setText(model.getValueAt(i,5).toString());
        pricingstd.setText(model.getValueAt(i,6).toString());
        pricingpro.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_jDisplayTableMouseClicked

    private void addvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvalueActionPerformed
                try{
                    JOptionPane.showMessageDialog(null, "Added");
                    name_final = name.getText();
                    String price1 = pricingstd.getText();
                    String price2 = pricingpro.getText();
                    String service = services.getText();
                    DefaultTableModel model = (DefaultTableModel)jDisplayTable.getModel();
                    Object[] row = new Object[8];
                    row[0]=entries_no++;
                    row[1]=name_final;
                    row[2]=service;
                    row[3]="NA";
                    row[4]="NA";
                    row[5]="NA";
                    row[6]=price1;
                    row[7]=price2;
                    pricestd_final=String.valueOf(Integer.parseInt(pricestd_final)+Integer.parseInt(price1));
                    pricepro_final=String.valueOf(Integer.parseInt(pricepro_final)+Integer.parseInt(price2));
                    model.addRow(row);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_addvalueActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton addvalue;
    private javax.swing.JButton book;
    public static javax.swing.JLabel displayUsr;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jAddressTag;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jDisplayTable;
    private javax.swing.JLabel jEmailTag;
    private javax.swing.JLabel jNameTag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPhonenumTag;
    private javax.swing.JLabel jPricingProTag;
    private javax.swing.JLabel jPricingStdTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jServicesTag;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pricingpro;
    private javax.swing.JTextField pricingstd;
    private javax.swing.JTextField services;
    // End of variables declaration//GEN-END:variables
}
