/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Aditi
 */
public class MenuOLD extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public MenuOLD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        extra = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        food = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        event = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        venue = new javax.swing.JPanel();
        jaipur = new javax.swing.JButton();
        udaipur = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        venuetype = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menu bar buttons");
        setBackground(new java.awt.Color(153, 0, 102));
        setLocation(new java.awt.Point(880, 515));
        setMaximumSize(new java.awt.Dimension(880, 515));
        setPreferredSize(new java.awt.Dimension(880, 515));
        setSize(new java.awt.Dimension(880, 515));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        extra.setBackground(new java.awt.Color(153, 0, 102));
        extra.setForeground(new java.awt.Color(255, 255, 255));
        extra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extraMouseExited(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(153, 0, 102));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("cards");
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton24MouseEntered(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(153, 0, 102));
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("Photography");
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton25MouseEntered(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(153, 0, 102));
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("Videography");
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton26MouseEntered(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(153, 0, 102));
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("Mehndi Artist");
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton27MouseEntered(evt);
            }
        });

        jButton28.setBackground(new java.awt.Color(153, 0, 102));
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("Make-up");
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton28MouseEntered(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(153, 0, 102));
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("Pandit");
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton29MouseEntered(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(153, 0, 102));
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("DJ");
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton30MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout extraLayout = new javax.swing.GroupLayout(extra);
        extra.setLayout(extraLayout);
        extraLayout.setHorizontalGroup(
            extraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        extraLayout.setVerticalGroup(
            extraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 10));

        food.setBackground(new java.awt.Color(255, 255, 255));
        food.setForeground(new java.awt.Color(255, 255, 255));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                foodMouseExited(evt);
            }
        });
        food.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jButton22.setBackground(new java.awt.Color(153, 0, 102));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Veg");
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton22MouseEntered(evt);
            }
        });
        food.add(jButton22);

        jButton23.setBackground(new java.awt.Color(153, 0, 102));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Non-veg");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton23MouseEntered(evt);
            }
        });
        food.add(jButton23);

        jPanel1.add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 90, 0));

        event.setBackground(new java.awt.Color(255, 255, 255));
        event.setForeground(new java.awt.Color(255, 255, 255));
        event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventMouseExited(evt);
            }
        });
        event.setLayout(new java.awt.GridLayout(6, 0, 5, 5));

        jButton16.setBackground(new java.awt.Color(153, 0, 102));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Engagement");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton16MouseEntered(evt);
            }
        });
        event.add(jButton16);

        jButton17.setBackground(new java.awt.Color(153, 0, 102));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Haldi");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
        });
        event.add(jButton17);

        jButton18.setBackground(new java.awt.Color(153, 0, 102));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Mehndi");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
        });
        event.add(jButton18);

        jButton19.setBackground(new java.awt.Color(153, 0, 102));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Sangeet");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton19MouseEntered(evt);
            }
        });
        event.add(jButton19);

        jButton20.setBackground(new java.awt.Color(153, 0, 102));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Shaadi");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton20MouseEntered(evt);
            }
        });
        event.add(jButton20);

        jButton21.setBackground(new java.awt.Color(153, 0, 102));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Reception");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton21MouseEntered(evt);
            }
        });
        event.add(jButton21);

        jPanel1.add(event, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 110, 0));

        venue.setBackground(new java.awt.Color(153, 0, 102));
        venue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                venueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                venueMouseExited(evt);
            }
        });
        venue.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

        jaipur.setBackground(new java.awt.Color(153, 0, 102));
        jaipur.setForeground(new java.awt.Color(255, 255, 255));
        jaipur.setText("Jaipur");
        jaipur.setBorder(null);
        jaipur.setBorderPainted(false);
        jaipur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jaipur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jaipurMouseEntered(evt);
            }
        });
        jaipur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaipurActionPerformed(evt);
            }
        });
        venue.add(jaipur);

        udaipur.setBackground(new java.awt.Color(153, 0, 102));
        udaipur.setForeground(new java.awt.Color(255, 255, 255));
        udaipur.setText("Udaipur");
        udaipur.setBorder(null);
        udaipur.setBorderPainted(false);
        udaipur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        udaipur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                udaipurMouseEntered(evt);
            }
        });
        udaipur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udaipurActionPerformed(evt);
            }
        });
        venue.add(udaipur);

        jButton5.setBackground(new java.awt.Color(153, 0, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Goa");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        venue.add(jButton5);

        jButton6.setBackground(new java.awt.Color(153, 0, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Kerala");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        venue.add(jButton6);

        jPanel1.add(venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 0));

        venuetype.setBackground(new java.awt.Color(153, 0, 102));
        venuetype.setForeground(new java.awt.Color(255, 255, 255));
        venuetype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                venuetypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                venuetypeMouseExited(evt);
            }
        });
        venuetype.setLayout(new java.awt.GridLayout(4, 0));

        jButton12.setBackground(new java.awt.Color(153, 0, 102));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Hotel");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        venuetype.add(jButton12);

        jButton13.setBackground(new java.awt.Color(153, 0, 102));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Resort");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton13MouseEntered(evt);
            }
        });
        venuetype.add(jButton13);

        jButton14.setBackground(new java.awt.Color(153, 0, 102));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Banquets");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton14MouseEntered(evt);
            }
        });
        venuetype.add(jButton14);

        jButton15.setBackground(new java.awt.Color(153, 0, 102));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("4 stars & above");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton15MouseEntered(evt);
            }
        });
        venuetype.add(jButton15);

        jPanel1.add(venuetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 0));

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setBackground(new java.awt.Color(153, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Venue");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton8.setBackground(new java.awt.Color(153, 0, 102));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Venue Type");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(153, 0, 102));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Event");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setBackground(new java.awt.Color(153, 0, 102));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Food");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton11.setBackground(new java.awt.Color(153, 0, 102));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Extra Services");
        jButton11.setBorder(null);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jPanel2.add(jButton11);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        jButton31.setBackground(new java.awt.Color(153, 0, 102));
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("Get Pricing");
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 140, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Enter number of guests-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, 30));

        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("guests...");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, 30));

        jButton1.setBackground(new java.awt.Color(153, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter Total Budget-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<4Lakhs", "4-10Lakhs", "10-20Lakhs", ">20Lakhs" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        setSize(new java.awt.Dimension(880, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void udaipurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udaipurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udaipurActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
       // venue.setSize(190,200);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       //  venue.setSize(0,0);
    }//GEN-LAST:event_jButton2MouseExited

    private void venueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venueMouseExited
       venue.setSize(0,0);
    }//GEN-LAST:event_venueMouseExited

    private void venueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venueMouseEntered
        venue.setSize(100,200);        // TODO add your handling code here:
    }//GEN-LAST:event_venueMouseEntered

    private void venueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venueMouseClicked
         venue.setSize(100,200);
    }//GEN-LAST:event_venueMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
                // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        venue.setSize(100,200);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jaipurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaipurMouseEntered
        // TODO add your handling code here:
        venue.setSize(100,200);
    }//GEN-LAST:event_jaipurMouseEntered

    private void jaipurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaipurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaipurActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        venue.setSize(100,200);// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
venue.setSize(100,200);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void udaipurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udaipurMouseEntered
venue.setSize(100,200);        // TODO add your handling code here:
    }//GEN-LAST:event_udaipurMouseEntered

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        venuetype.setSize(160,200);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
//venuetype.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseExited

    private void venuetypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venuetypeMouseEntered
venuetype.setSize(160,200);        // TODO add your handling code here:
    }//GEN-LAST:event_venuetypeMouseEntered

    private void venuetypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venuetypeMouseExited
        venuetype.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_venuetypeMouseExited

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        venuetype.setSize(160,200);// TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseEntered
        venuetype.setSize(160,200);// TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseEntered

    private void jButton14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseEntered
           venuetype.setSize(160,200);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14MouseEntered

    private void jButton15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseEntered
        venuetype.setSize(160,200);// TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseEntered

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
    event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void eventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventMouseEntered
      event.setSize(150,250);  // TODO add your handling code here:
    }//GEN-LAST:event_eventMouseEntered

    private void jButton16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseEntered
event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MouseEntered

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
      event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseEntered
      event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MouseEntered

    private void jButton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseEntered
         event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseEntered

    private void jButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseEntered
  event.setSize(150,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
// event.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseExited

    private void eventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventMouseExited
     event.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_eventMouseExited

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
         food.setSize(100,130);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseEntered
food.setSize(100,130);        // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseEntered

    private void jButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseEntered
food.setSize(100,130);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseEntered

    private void jButton23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseEntered
food.setSize(100,130);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
//food.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseExited

    private void foodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseExited
food.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseExited

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        extra.setSize(130,250);// TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void extraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraMouseEntered
         extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_extraMouseEntered

    private void jButton24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseEntered
 extra.setSize(130,250);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton24MouseEntered

    private void jButton25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseEntered
 extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25MouseEntered

    private void jButton26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseEntered
extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseEntered

    private void jButton27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseEntered
extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27MouseEntered

    private void jButton28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseEntered
extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28MouseEntered

    private void jButton29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseEntered
extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29MouseEntered

    private void jButton30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseEntered
extra.setSize(130,250);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
//extra.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseExited

    private void extraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraMouseExited
extra.setSize(0,0);        // TODO add your handling code here:
    }//GEN-LAST:event_extraMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the Menu */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOLD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel event;
    private javax.swing.JPanel extra;
    private javax.swing.JPanel food;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jaipur;
    private javax.swing.JButton udaipur;
    private javax.swing.JPanel venue;
    private javax.swing.JPanel venuetype;
    // End of variables declaration//GEN-END:variables
}
